version: "2"
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5671-5672:5671-5672" # client connectors
      - "9393:15672" # Admin webpage


  exchangeDB:
    image: exchangedb
    ports:
      - "5432:5432"

  exchangeNode1:
    image: exchange-node
    environment:
      RABBIT_HOSTNAME: rabbit
      INSTRUMENTS: AMZN,GOOG
    links:
      - rabbit
      - exchangeDB

#  exchangeNode2:
#    image: exchange-node
#    environment:
#      RABBIT_HOSTNAME: rabbit
#      INSTRUMENTS: WBC,CBA
#    links:
#      - rabbit
#      - exchangeDB


  exchangeweb:
    image: exchange-web
    ports:
      - "8888:8080"
    environment:
      RABBIT_HOSTNAME: rabbit
      INSTRUMENTS: AMZN,GOOG,WBC,CBA
    links:
      - rabbit




