version: "2"
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5671-5672" # client connectors
      - "15672" # Admin webpage
    networks:
      - exchange


  exchangeDB:
    image: 192.168.160.235:5000/exchangedb
    ports:
      - "5432:5432"
    networks:
      - exchange

  orderMatcher1:
    image: 192.168.160.235:5000/exchange-node
    environment:
      RABBIT_HOSTNAME: rabbit
      INSTRUMENTS: AMZN,GOOG
    networks:
      - exchange


  orderMatcher2:
    image: 192.168.160.235:5000/exchange-node
    environment:
      RABBIT_HOSTNAME: rabbit
      INSTRUMENTS: WBC,CBA
    networks:
      - exchange


  exchangeweb:
    image: 192.168.160.235:5000/exchange-web
    ports:
      - "8080"
    environment:
      RABBIT_HOSTNAME: rabbit
      INSTRUMENTS: AMZN,GOOG,WBC,CBA
    networks:
      - exchange

networks:
  exchange:
    driver: overlay


