export var instrument_list_url='/instruments'
export var order_submit_url='/orders'
export var snapshot_url='/snapshot'
export var order_search_url='/orders'
export var snapshot_updates_url='/exchange'
export var order_updates_url='/exchange'
export var private_trade_updates_url='/exchange'
export var public_trade_updates_url='/exchange'

// Use this for local development (have to update /etc/hosts/ with a valid value for exchange.sorted.net
//export var instrument_list_url='http://exchange.sorted.net:8888/instruments'
//export var order_submit_url='http://doug:password@exchange.sorted.net:8888/orders'
//export var snapshot_url='http://doug:password@exchange.sorted.net:8888/snapshot'
//export var order_search_url='http://doug:password@exchange.sorted.net:8888/orders'
//export var snapshot_updates_url='http://doug:password@exchange.sorted.net:8888/exchange'
//export var order_updates_url='http://doug:password@exchange.sorted.net:8888/exchange'
//export var private_trade_updates_url='http://doug:password@exchange.sorted.net:8888/exchange'
//export var public_trade_updates_url='http://doug:password@exchange.sorted.net:8888/exchange'