export var instrument_list_url='http://exchange.sorted.net:8888/instruments'
export var order_submit_url='http://exchange.sorted.net:8888/orders'
export var snapshot_url='http://exchange.sorted.net:8888/snapshot'
export var order_search_url='http://exchange.sorted.net:8888/orders'
export var snapshot_updates_url='http://exchange.sorted.net:8888/exchange'
export var order_updates_url='http://exchange.sorted.net:8888/exchange'
export var private_trade_updates_url='http://exchange.sorted.net:8888/exchange'
export var public_trade_updates_url='http://exchange.sorted.net:8888/exchange'